import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "@/app/theme-provider";
import StoreProvider from "@/app/StoreProvider";

const roboto = Roboto({subsets: ["latin"], weight: ["300", "400", "500", "700"]});

export const metadata: Metadata = {
    title: "S shop",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
        <head>
            <title>S Shop</title>
            <link rel="icon" href="/favicon.ico" sizes="any"/>
            <link
                rel="apple-touch-icon"
                href="/apple-touch-icon.png?<generated>"
                type="image/<generated>"
                sizes="<generated>"
            />
        </head>
        <body className={roboto.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <StoreProvider>
                {children}
            </StoreProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
