import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "@/app/theme-provider";
import StoreProvider from "@/app/StoreProvider";
import {GoogleOAuthProvider} from '@react-oauth/google';
import {clientId} from "@/app/constants";

const roboto = Roboto({subsets: ["latin"], weight: ["300", "400", "500", "700"]});

export const metadata: Metadata = {
    title: "S Tech - business platform",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" suppressHydrationWarning>
        <head>
            <link rel="icon" href="/favicon.ico" sizes="any"/>
            <link
                rel="apple-touch-icon"
                href="/apple-touch-icon.png?<generated>"
                type="image/<generated>"
                sizes="<generated>"
            />
        </head>
        <body className={roboto.className}>
        <GoogleOAuthProvider clientId="29284238727-9b23tun95m6npubqee97c52hahd44qfs.apps.googleusercontent.com">
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <StoreProvider>
                    {children}
                </StoreProvider>
            </ThemeProvider>
        </GoogleOAuthProvider>;
        </body>
        </html>
    );
}
